module AttributeTable exposing (attributeTable)


import Html exposing (..)
import Html.Attributes exposing (..)
import Html.Events exposing (..)
import Messages exposing (..)

import Character exposing (Character, attrValue)

attributeTable : Character -> Bool -> (Html Msg)
attributeTable model buttons =
  let
    head = if buttons then
            thead []
              [ tr []
                  [ th [] [ text "Name" ]
                  , th [] [ text "Value" ]
                  , th [] [ text "XP" ]
                  , th [] [ text "Increment" ]
                  , th [] [ text "Decrement" ]
                  ]
              ]
          else
            thead []
              [ tr []
                  [ th [] [ text "Name" ]
                  , th [] [ text "Value" ]
                  , th [] [ text "XP" ]
                  ]
              ]
    baseBody : List (Html Msg)
    baseBody = 
      [ tr []
          [ td [] [ text "STR" ]
          , td [] [ text <| toString <| attrValue model "STR" ]
          , td [] [ text <| toString model.attributes.str ]
          ]
      , tr []
          [ td [] [ text "BOD" ]
          , td [] [ text <| toString <| attrValue model "BOD" ]
          , td [] [ text <| toString model.attributes.bod ]
          ]
      , tr []
          [ td [] [ text "RFL" ]
          , td [] [ text <| toString <| attrValue model "RFL" ]
          , td [] [ text <| toString model.attributes.rfl ]
          ]
      , tr []
          [ td [] [ text "DEX" ]
          , td [] [ text <| toString <| attrValue model "DEX" ]
          , td [] [ text <| toString model.attributes.dex ]
          ]
      , tr []
          [ td [] [ text "INT" ]
          , td [] [ text <| toString <| attrValue model "INT" ]
          , td [] [ text <| toString model.attributes.int ]
          ]
      , tr []
          [ td [] [ text "WIL" ]
          , td [] [ text <| toString <| attrValue model "WIL" ]
          , td [] [ text <| toString model.attributes.wil ]
          ]
      , tr []
          [ td [] [ text "CHA" ]
          , td [] [ text <| toString <| attrValue model "CHA" ]
          , td [] [ text <| toString model.attributes.cha ]
          ]
      , tr []
          [ td [] [ text "EDG" ]
          , td [] [ text <| toString <| attrValue model "EDG" ]
          , td [] [ text <| toString model.attributes.edg ]
          ]
      ]
    body = if buttons then
      tbody []
        [ tr []
            [ td [] [ text "STR" ]
            , td [] [ text <| toString <| attrValue model "STR" ]
            , td [] [ text <| toString model.attributes.str ]
            , td [] [ button [ class "btn btn-success", onClick AddStr ] [ text "+" ] ]
            , td [] [ button [ class "btn btn-error", onClick DecStr ] [ text "-" ] ]
            ]
        , tr []
            [ td [] [ text "BOD" ]
            , td [] [ text <| toString <| attrValue model "BOD" ]
            , td [] [ text <| toString model.attributes.bod ]
            , td [] [ button [ class "btn btn-success", onClick AddBod ] [ text "+" ] ]
            , td [] [ button [ class "btn btn-error", onClick DecBod ] [ text "-" ] ]
            ]
        , tr []
            [ td [] [ text "RFL" ]
            , td [] [ text <| toString <| attrValue model "RFL" ]
            , td [] [ text <| toString model.attributes.rfl ]
            , td [] [ button [ class "btn btn-success", onClick AddRfl ] [ text "+" ] ]
            , td [] [ button [ class "btn btn-error", onClick DecRfl ] [ text "-" ] ]
            ]
        , tr []
            [ td [] [ text "DEX" ]
            , td [] [ text <| toString <| attrValue model "DEX" ]
            , td [] [ text <| toString model.attributes.dex ]
            , td [] [ button [ class "btn btn-success", onClick AddDex ] [ text "+" ] ]
            , td [] [ button [ class "btn btn-error", onClick DecDex ] [ text "-" ] ]
            ]
        , tr []
            [ td [] [ text "INT" ]
            , td [] [ text <| toString <| attrValue model "INT" ]
            , td [] [ text <| toString model.attributes.int ]
            , td [] [ button [ class "btn btn-success", onClick AddInt ] [ text "+" ] ]
            , td [] [ button [ class "btn btn-error", onClick DecInt ] [ text "-" ] ]
            ]
        , tr []
            [ td [] [ text "WIL" ]
            , td [] [ text <| toString <| attrValue model "WIL" ]
            , td [] [ text <| toString model.attributes.wil ]
            , td [] [ button [ class "btn btn-success", onClick AddWil ] [ text "+" ] ]
            , td [] [ button [ class "btn btn-error", onClick DecWil ] [ text "-" ] ]
            ]
        , tr []
            [ td [] [ text "CHA" ]
            , td [] [ text <| toString <| attrValue model "CHA" ]
            , td [] [ text <| toString model.attributes.cha ]
            , td [] [ button [ class "btn btn-success", onClick AddCha ] [ text "+" ] ]
            , td [] [ button [ class "btn btn-error", onClick DecCha ] [ text "-" ] ]
            ]
        , tr []
            [ td [] [ text "EDG" ]
            , td [] [ text <| toString <| attrValue model "EDG" ]
            , td [] [ text <| toString model.attributes.edg ]
            , td [] [ button [ class "btn btn-success", onClick AddEdg ] [ text "+" ] ]
            , td [] [ button [ class "btn btn-error", onClick DecEdg ] [ text "-" ] ]
            ]
        ]
    else
      tbody [] baseBody
  in
    table []
      [ head
      , body
      ]
